### ISSUE TITLE
Wifi issues with 5.15  

### ISSUE THREAD

**Issue by robcxyz** [tuxedocomputers/linux-meta#1]
Hi, 

I am  having wifi issues with 5.15 similar to others reporting in this issue -> https://askubuntu.com/questions/1403954/wifi-issues-in-ubuntu-22-04lts

Do you have a timeline for upgrading to 5.17 which seems to not have the wifi issue? Is this something that is ok to be done manually?

**Comment by robcxyz** [comment]
Hi, this is still an issue with 6.0 / 6.1 

Basically any time needing to login through some public wifi that requires some pop up authentication.

**Comment by Matombo** [comment]
If the issue persist please open an issue here: https://gitlab.com/tuxedocomputers/development/packages/linux
